# Generated by Django 2.0.4 on 2018-04-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitem',
            name='image_url',
            field=models.URLField(null=True),
        ),
    ]
