# Generated by Django 2.0.4 on 2018-04-26 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20180426_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
