# Generated by Django 2.0.4 on 2018-05-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0004_poll_auther'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='auther',
            field=models.CharField(default='佚名', editable=False, max_length=100),
        ),
    ]
